---
title: "Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidycode)
library(tidyverse)
library(wordcloud)
```


### Leitura dos dados
```{r}
files_camara <- read.delim("../data/all-camara-files.txt", header = FALSE)
files_tse <- read.delim("../data/all-tse-files.txt", header = FALSE)

files_camara_vec <- files_camara %>% unlist() %>% as.vector()
files_tse_vec <- files_tse %>% unlist() %>% as.vector()
```


### Lendo os arquivos através da biblioteca tidycode
```{r}
camara_data = read_rfiles(files_camara_vec)
tse_data <- read_rfiles(files_tse_vec)
```


### Removendo expressões que a biblioteca não foi capaz de ler
```{r}
tse_data_clean <- tse_data %>%
  filter(!(row_number() %in% c(1529, 1536, 1544, 1545, 4893, 10224, 11149, 11151, 11154, 11165)))


camara_data_clean <- camara_data %>%
  filter(!(row_number() %in% c(136, 392, 469, 3800)))
```


### Gera dados _unnested_
```{r}
tse_unnested <- tse_data_clean %>% unnest_calls(expr)
camara_unnested <- camara_data_clean %>% unnest_calls(expr)
```

### Classifica funções
```{r}
tse_classified <- tse_unnested  %>%
  select(func, args) %>%
  inner_join(get_classifications("crowdsource", include_duplicates=FALSE))

camara_classified <- camara_unnested  %>%
  select(func, args) %>%
  inner_join(get_classifications("crowdsource", include_duplicates=FALSE))



```

### Remove as _stopfuncs_
```{r}
camara_classified_clean <- camara_classified %>% anti_join(get_stopfuncs())
tse_classified_clean <- tse_classified %>% anti_join(get_stopfuncs())


camara_classified_clean %>%
  select(-args) %>% 
  write_csv("../data/camara_classified_clean.csv")

tse_classified_clean %>%
  select(-args) %>% 
  write_csv("../data/tse_classified_clean.csv")
```

```{r}
# all_data <- camara_classified_clean %>%
#   select(-args) %>%
#   mutate(fonte = "Câmara") %>%
#   union(tse_classified_clean %>%
#           select(-args) %>%
#           mutate(fonte = "TSE"))


tse_ <- tse_classified_clean %>%
          select(-args) %>%
          mutate(fonte = "TSE")

camara_ <- camara_classified_clean %>%
  select(-args) %>%
  mutate(fonte = "Câmara")


all_data_ <- tse_ %>%
    rbind(camara_)

```



```{r}
camara_classified_clean %>%
  group_by(classification) %>%
  summarise(n = n()) %>%
  ggplot(aes(x= reorder(classification, n), y = n)) +
  geom_bar(stat = "identity", fill="#3C7A89") +
  coord_flip() + 
  theme_bw() +
  labs(x = "Nº de observações", y = "Categoria") +
  scale_fill_continuous(name = "")

  ggsave("p1-camara.pdf")

camara_classified %>%
  group_by(classification) %>%
  summarise(n = n()) %>%
  ggplot(aes(x= reorder(classification, n), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  theme_bw() +
  labs(x = "Nº de observações", y = "Categoria")


camara_classified_clean %>%
  group_by(classification) %>%
  summarise(n = n(), 
            distinct = n_distinct(func)) %>%
  ggplot(aes(x= reorder(classification, n), y = n)) +
  geom_bar(stat = "identity", fill="#3C7A89", position="dodge") +
  coord_flip() + 
  theme_bw() +
  labs(x = "Nº de observações", y = "Categoria") +
  scale_fill_continuous(name = "")


camara_agg <- camara_classified_clean %>%
  group_by(classification) %>%
  summarise(n = n(), 
            distinct = n_distinct(func),
            prop = n()/nrow(camara_classified_clean)) %>%
  mutate(fonte = "Câmara")


tse_agg <- tse_classified_clean %>%
  group_by(classification) %>%
  summarise(n = n(), 
            distinct = n_distinct(func),
            prop = n()/nrow(tse_classified_clean)) %>%
  mutate(fonte = "TSE")

all_data_agg <- camara_agg %>% rbind(tse_agg)

all_data_agg %>%
  ggplot(aes(x= reorder(classification, prop), y = prop, fill=fonte)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() + 
  theme_bw() +
  labs(y = "Proporção de observações", x = "Categoria") +
  scale_fill_discrete(name = "")
ggsave("props.pdf")

all_data_ %>%
  group_by(classification, fonte) %>%
  summarise(n = n()) %>%
  ggplot(aes(x= reorder(classification, n), y = n, fill=fonte)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() + 
  theme_bw() +
  labs(x = "Nº de observações", y = "Categoria") +
  scale_fill_discrete(name = "")
```
```{r}
# diferença das proporções
data_diff <- camara_agg %>%
  inner_join(tse_agg, by = "classification") %>%
  mutate(diff = prop.x - prop.y)

# camara = x
# tse = y

data_diff %>%
  ggplot(aes(x=reorder(classification, diff))) +
  geom_col(aes(y=diff, fill = !(diff > 0)), width = .7) +
  coord_flip() + 
  theme_bw() +
  labs(
        y = "Diferença entre as proporções",
        x = "Categoria"
    ) +
    coord_flip() + 
    scale_fill_discrete(name = "", labels = c("Câmara", "TSE"))

ggsave("diff.pdf")
```


```{r}

tse_classified_clean %>%
  group_by(classification) %>%
  summarise(n = n()) %>%
  ggplot(aes(x= reorder(classification, n), y = n)) +
  geom_bar(stat = "identity", fill="#561F37") +
  coord_flip() + 
  theme_bw() +
  labs(x = "Nº de observações", y = "Categoria") +
  scale_fill_continuous(name = "")

ggsave("p1-tse.pdf")

tse_classified %>%
  group_by(classification) %>%
  summarise(n = n()) %>%
  ggplot(aes(x= reorder(classification, n), y = n, fill=n)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  theme_bw()
```


```{r}
tse_classified_clean %>%
  count(classification, func) %>%
  with(
    wordcloud(func, n, min.freq = 10,
              colors = brewer.pal(9, "Set1")[factor(.$classification)],
              random.order = FALSE,
              ordered.colors = TRUE)
  )
```



```{r}
camara_classified_clean %>%
  count(classification, func) %>%
  with(
    wordcloud(func, n, min.freq = 10,
              colors = brewer.pal(9, "Set1")[factor(.$classification)],
              random.order = FALSE,
              ordered.colors = TRUE)
  )
```

```{r}
camara_classified_clean %>%
  filter(classification %in% c("data cleaning", "exploratory", "modeling", "visualization")) %>%
  group_by(classification, func) %>% 
  tally()  %>%
  top_n(5) %>%
  ggplot(aes(reorder(func, n), n, fill=classification)) +
  theme_bw() +
  geom_col(show.legend = FALSE) +
  facet_wrap(~classification, scales = "free_y") +
  scale_x_discrete(element_blank()) +
  scale_y_continuous("Câmara - Top 5 funções") +
  coord_flip()

ggsave("top-camara.pdf")
```

```{r}
tse_classified_clean %>%
  filter(classification %in% c("data cleaning", "exploratory", "modeling", "visualization")) %>%
  group_by(classification, func) %>% 
  tally()  %>%
  top_n(5) %>%
  ggplot(aes(reorder(func, n), n, fill=classification)) +
  theme_bw() +
  geom_col(show.legend = FALSE) +
  facet_wrap(~classification, scales = "free_y") +
  scale_x_discrete(element_blank()) +
  scale_y_continuous("TSE - Top 5 funções de cada tipo") +
  coord_flip()

ggsave("top-tse.pdf")
```



